services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    restart: on-failure
    command: ["uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "8000"]
    healthcheck:
      test: curl --fail http://localhost:8000/health || exit 1
      interval: 30s
      timeout: 150s
      retries: 3
      start_period: 10s
    environment:
      OPEN_AI_API_KEY: ${OPEN_AI_API_KEY}

  autoheal:
    restart: always
    image: willfarrell/autoheal
    environment:
      - AUTOHEAL_CONTAINER_LABEL=all
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock